services:
  - type: web
    plan: free
    name: Django_Assurance
    runtime: python
    buildCommand: "./build.sh"
    startCommand: >
      python manage.py migrate &&
      python -m gunicorn Django_Assurance.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_assurance_db  # Mets le bon nom ici !
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
