services:
  - type: web
    plan: free
    name: Django_Assurance
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Django_Assurance.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-cudoasdumphs73cqsk10-a
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
