# Generated by Django 5.1.5 on 2025-01-30 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="staff_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_with_staff",
                to="user.staffuser",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="staff_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="user.staffuser",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("staff_user", "date", "start_time", "end_time")},
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("staff_user", "day_of_week", "start_time", "end_time")},
        ),
    ]
