# Generated by Django 5.1.5 on 2025-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mail", models.CharField(max_length=250)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField(null=True)),
            ],
        ),
    ]
